steps:
- name: 'gcr.io/mobilelive-design-thinking/ml-design'
  args: ['build', '-t', 'gcr.io/mobilelive-design-thinking/my-image', '.']
  timeout: 500s
- name: 'gcr.io/mobilelive-design-thinking/ml-design'
  args: ['push', 'gcr.io/mobilelive-design-thinking/my-image']